name: my-code-server

on:   
  push:
jobs:
  build0:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER }}
  build1:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER2 }}
  build2:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER3 }}
  build3:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER4 }}
  build4:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER5 }}
  build5:
    runs-on: ubuntu-24.04-arm
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER6 }}
