name: my-code-server

on:   
  push:
jobs:
  build0:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER }}
  build1:
    runs-on: ubuntu-24.04
    steps: 
      - name: build-code-server
        continue-on-error: true
        run: ${{ secrets.CODESERVER3 }}
